# Contenedor de origen
FROM ubuntu:16.04                                   
MAINTAINER Luis Gallego <lgaq94@gmail.com>
# Directorio de trabajo,en él se va a entrar cuando se ejecute algo en el contenedor
WORKDIR /root
# Indica qué se va a ejecutar en caso de que se ejecute el contenedor directamente
#CMD ["/usr/local/bin/sbt"]

# Ejecutamos ordenes
RUN mkdir prueba1
