# -*- mode: ruby -*-
# vi: set ft=ruby :

# Plugin Vagrant - Azure
require 'vagrant-azure'

Vagrant.configure("2") do |config|

  config.vm.box = "azure-dummy"    # Azure box dummy
  config.ssh.private_key_path = '~/.ssh/id_rsa' # Indicamos ruta ssh clave privada
  
  config.vm.provider "azure" do |az, override|  # Parametros para AZURE 

    az.tenant_id = ENV['AZURE_TENANT_ID'] 
    az.client_id = ENV['AZURE_CLIENT_ID'] 
    az.client_secret = ENV['AZURE_CLIENT_SECRET'] 
    az.subscription_id = ENV['AZURE_SUBSCRIPTION_ID']

    # Datos de la MV
    az.vm_name = 'ponerNombreWay'
    az.vm_size = 'Standard_B1s'
    az.vm_image_urn = 'Canonical:UbuntuServer:16.04-LTS:latest'
    az.resource_group_name = 'ponerNombreRecursosWay'    
  end

end 